### DataFrame
It is a 2-D object containing index and multiple columns of content, with each column having a label.<br>
**DataFrame = Two-Axis Labelled Array**<br>
Part of Pandas Library

In [1]:
import pandas as pd

# 3 school records
r1 = pd.Series({'Name' : 'Alice', 'Class' : 'Physics', 'Score' : 85})

r2 = pd.Series({'Name' : 'Jack', 'Class' : 'Chemistry', 'Score' : 82})

r3 = pd.Series({'Name' : 'Helen', 'Class' : 'Biology', 'Score' : 90})

In [10]:
# DataFrame object is indexed
# DataFrame represents group of series where each series represents a row of data
# Just like series, we can pass an array and index values as second arguments

df = pd.DataFrame([r1,r2,r3], index=['s1','s2','s3'])
df

     Name      Class  Score
s1  Alice    Physics     85
s2   Jack  Chemistry     82
s3  Helen    Biology     90

In [17]:
# Alternative is to use Dictionary
fd = [
{'name':'Shreyas','alias':'Turtle'},
{'name': 'Deekshith','alias':'Kardi'},{'name':'Zain','alias':'Xain Grylls'},{'name':'Navya','alias':'Nivea'},{'name':'Sumaiya','alias':'Suman'},{'name':'Tejaswini','alias':'Turtle'}]

f = pd.DataFrame(fd)
f

        name        alias
0    Shreyas       Turtle
1  Deekshith        Kardi
2       Zain  Xain Grylls
3      Navya        Nivea
4    Sumaiya        Suman
5  Tejaswini       Turtle

In [1]:
import pandas as pd

data = {
'index' : ['shreyas','siri', 'sangi', 'satya'],
'data' : ['aiml', 'pcmb', 'cbz', 'eee'],
'name' : 'studies'
}

print(pd.DataFrame(data))

     index  data     name
0  shreyas  aiml  studies
1     siri  pcmb  studies
2    sangi   cbz  studies
3    satya   eee  studies