In [19]:
# Grouping the multi-indexed df
import pandas as pd
s = pd.Series({'ckm' : 'coffee', 'blr' : 'tech', 'mys' : 'kings'})
df = s.to_frame('famous')
df['temp'] = ['cold', 'hot', 'avg']
df

     famous  temp
ckm  coffee  cold
blr    tech   hot
mys   kings   avg

In [20]:
# Add a new tuple using .loc[]
df.loc['has'] = ['malls', 'avg']
df.loc['dvg'] = ['peda', 'hot']
df

     famous  temp
ckm  coffee  cold
blr    tech   hot
mys   kings   avg
has   malls   avg
dvg    peda   hot

In [22]:
df = df.reset_index()
df = df.sort_values(by='temp')
df = df.set_index(['temp', 'index'])
df

            famous
temp index
avg  mys     kings
     has     malls
cold ckm    coffee
hot  blr      tech
     dvg      peda

In [24]:
for group, frame in df.groupby(level = [0,1]):
    print(group)

('avg', 'has')
('avg', 'mys')
('cold', 'ckm')
('hot', 'blr')
('hot', 'dvg')

In [26]:
for group, frame in df.groupby(level = (0,1)):
    print(group)
    print('\n', frame)
    print('--------------')

('avg', 'has')

            famous
temp index
avg  has    malls
--------------
('avg', 'mys')

            famous
temp index
avg  mys    kings
--------------
('cold', 'ckm')

             famous
temp index
cold ckm    coffee
--------------
('hot', 'blr')

            famous
temp index
hot  blr     tech
--------------
('hot', 'dvg')

            famous
temp index
hot  dvg     peda
--------------

In [27]:
# Groupby using only on temp
for group, frame in df.groupby('temp') :
    print(group)
    print('\n', frame)
    print('--------------')

avg

            famous
temp index
avg  mys    kings
     has    malls
--------------
cold

             famous
temp index
cold ckm    coffee
--------------
hot

            famous
temp index
hot  blr     tech
     dvg     peda
--------------