### Merging One or More DataFrames

Full Outer Join -> Union<br>
Inner Join -> Intersection

In [2]:
import pandas as pd


stdf = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])

stdf = stdf.set_index('Name')

sdf = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])

sdf = sdf.set_index('Name')

In [3]:
stdf # Staff

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

In [4]:
sdf # Student

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [5]:
# James and Sally are both Students and Staff, but Mike is not

# Creating Union
pd.merge(stdf,sdf, how='outer', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [6]:
# Intersection
pd.merge(stdf,sdf, how='inner', left_index=True, right_index=True)

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

In [7]:
# left-Join
pd.merge(stdf,sdf, how='left', left_index=True, right_index=True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

In [8]:
# Right-Join
pd.merge(stdf,sdf, how='right', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering

In [9]:
# We need not use Indexes to merge df, param called "on"

# Remove index
stdf = stdf.reset_index()
sdf = sdf.reset_index()

# Join based on name column
pd.merge(stdf, sdf, how='right', on='Name') # Mistake

    Name            Role       School
0  James          Grader     Business
1   Mike             NaN          Law
2  Sally  Course liasion  Engineering

In [10]:
stdf = stdf.reset_index()
stdf

   index   Name            Role
0      0  Kelly  Director of HR
1      1  Sally  Course liasion
2      2  James          Grader

In [11]:
sdf = sdf.reset_index()
sdf

   index   Name       School
0      0  James     Business
1      1   Mike          Law
2      2  Sally  Engineering

In [12]:
pd.merge(stdf, sdf, how='right', on='Name')

# Always reset the index of dataframe before merging them

   index_x   Name            Role  index_y       School
0      2.0  James          Grader        0     Business
1      NaN   Mike             NaN        1          Law
2      1.0  Sally  Course liasion        2  Engineering

In [13]:
# Better to use df.reset_index(drop = True)
# This removes earlier index
# Example ->

sample = pd.DataFrame(
    [
        ['Charlie', 'Comedy'],
        ['Gabbar', 'Action'],
        ['Bheem', 'Cartoon']
    ],
    columns = ['Name', 'Type']
)
sample

      Name     Type
0  Charlie   Comedy
1   Gabbar   Action
2    Bheem  Cartoon

In [14]:
sample = sample.set_index('Name')
sample

            Type
Name
Charlie   Comedy
Gabbar    Action
Bheem    Cartoon

In [15]:
sample.reset_index(drop=True) # Dangerous

      Type
0   Comedy
1   Action
2  Cartoon

### Handling Conflicts between df

In [16]:
stdf = pd.DataFrame(
    [
        {"Name": "Kelly", "Role": "Director of HR", "Location": "State Street"},
        {"Name": "Sally", "Role": "Course liasion", "Location": "Washington Avenue"},
        {"Name": "James", "Role": "Grader", "Location": "Washington Avenue"},
    ]
)
sdf = pd.DataFrame(
    [
        {"Name": "James", "School": "Business", "Location": "1024 Billiard Avenue"},
        {"Name": "Mike", "School": "Law", "Location": "Fraternity House #22"},
        {"Name": "Sally", "School": "Engineering", "Location": "512 Wilson Crescent"},
    ]
)

In [17]:
stdf

    Name            Role           Location
0  Kelly  Director of HR       State Street
1  Sally  Course liasion  Washington Avenue
2  James          Grader  Washington Avenue

In [18]:
sdf

    Name       School              Location
0  James     Business  1024 Billiard Avenue
1   Mike          Law  Fraternity House #22
2  Sally  Engineering   512 Wilson Crescent

In [19]:
# _x -> Left df index
# _y -> Right df index

# If we want all staff info regardless of whether they were students or not. But if they were students, we would want to get their student details as well -> Solution is left join

pd.merge(stdf, sdf, how='left', on='Name')

    Name            Role         Location_x       School            Location_y
0  Kelly  Director of HR       State Street          NaN                   NaN
1  Sally  Course liasion  Washington Avenue  Engineering   512 Wilson Crescent
2  James          Grader  Washington Avenue     Business  1024 Billiard Avenue

In [20]:
# Multi-indexing and Multi-columns

stdf = pd.DataFrame(
    [
        {"First Name": "Kelly", "Last Name": "Desjardins", "Role": "Director of HR"},
        {"First Name": "Sally", "Last Name": "Brooks", "Role": "Course liasion"},
        {"First Name": "James", "Last Name": "Wilde", "Role": "Grader"},
    ]
)
sdf = pd.DataFrame(
    [
        {"First Name": "James", "Last Name": "Hammond", "School": "Business"},
        {"First Name": "Mike", "Last Name": "Smith", "School": "Law"},
        {"First Name": "Sally", "Last Name": "Brooks", "School": "Engineering"},
    ]
)

In [21]:
stdf

  First Name   Last Name            Role
0      Kelly  Desjardins  Director of HR
1      Sally      Brooks  Course liasion
2      James       Wilde          Grader

In [22]:
sdf

  First Name Last Name       School
0      James   Hammond     Business
1       Mike     Smith          Law
2      Sally    Brooks  Engineering

In [26]:
# James Wilde and James Hammond are separate names hence won't be included in Inner Join

pd.merge(stdf, sdf, how='inner', on=['First Name', 'Last Name']) # Use list of columns

  First Name Last Name            Role       School
0      Sally    Brooks  Course liasion  Engineering

### Concatenating DataFrames <br>
Joining -> Horizontally <br>
Concatenating -> Vertically

In [28]:
%%capture

df_2011 = pd.read_csv(
    "datasets/college_scorecard/MERGED2011_12_PP.csv",
    on_bad_lines='skip'
)

df_2012 = pd.read_csv(
    "datasets/college_scorecard/MERGED2012_13_PP.csv",
    on_bad_lines='skip'
)

df_2013 = pd.read_csv(
    "datasets/college_scorecard/MERGED2013_14_PP.csv",
    on_bad_lines='skip'
)

In [30]:
df_2011.head(3)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654.0,100200.0,1002,Alabama A & M University,Normal,AL,35762,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663.0,105200.0,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100690.0,2503400.0,25034,Amridge University,Montgomery,AL,36117-3553,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
print(len(df_2011))
print(len(df_2012))
print(len(df_2013))

15235
7793
7804

In [35]:
frames = [df_2011, df_2012, df_2013]
len(pd.concat(frames))

30832

In [37]:
# Concatenation is Successful
# Problem is that we don't know which data is from which layer
# Hence we can set an extra level of index

pd.concat(frames, keys=['2011', '2012', '2013']).sample(10)

              UNITID      OPEID OPEID6  \
2011 11810  444547.0  3810500.0  38105
2013 1360   154952.0   190200.0   1902
     2217   182290.0   256800.0   2568
2011 10510  420556.0  4151900.0  41519
     9115   364566.0  2345800.0  23458
2012 836    136400.0  1065200.0  10652
2013 6110   450067.0  1031905.0  10319
2012 3294   211909.0   918600.0   9186
2011 6580   211608.0   331700.0   3317
     9711   383251.0  3064400.0  30644

                                            INSTNM             CITY STABBR  \
2011 11810                        Mid City College      Baton Rouge     LA
2013 1360          Cowley County Community College    Arkansas City     KS
     2217                University of Nevada-Reno             Reno     NV
2011 10510        Columbia Gorge Community College       The Dalles     OR
     9115                Montebello Beauty College       Montebello     CA
2012 836              Pasco-Hernando State College  New Port Richey     FL
2013 6110                Fortis College-Cincinnati       Cincinnati     OH
2012 3294             Dean Institute of Technology       Pittsburgh     PA
2011 6580       Cheyney University of Pennsylvania          Cheyney     PA
     9711   Regency Beauty Institute-Winston-Salem    Winston-Salem     NC

                   ZIP  ACCREDAGENCY INSTURL NPCURL  ...  \
2011 11810  70806-0000           NaN     NaN    NaN  ...
2013 1360        67005           NaN     NaN    NaN  ...
     2217        89557           NaN     NaN    NaN  ...
2011 10510       97058           NaN     NaN    NaN  ...
     9115        90640           NaN     NaN    NaN  ...
2012 836    34654-5199           NaN     NaN    NaN  ...
2013 6110        45246           NaN     NaN    NaN  ...
2012 3294   15226-1197           NaN     NaN    NaN  ...
2011 6580   19319-0200           NaN     NaN    NaN  ...
     9711        27103           NaN     NaN    NaN  ...

           OMAWDP8_NOTFIRSTTIME_POOLED_SUPP OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
2011 11810                              NaN                              NaN
2013 1360                               NaN                              NaN
     2217                               NaN                              NaN
2011 10510                              NaN                              NaN
     9115                               NaN                              NaN
2012 836                                NaN                              NaN
2013 6110                               NaN                              NaN
2012 3294                               NaN                              NaN
2011 6580                               NaN                              NaN
     9711                               NaN                              NaN

           OMENRYP_FULLTIME_POOLED_SUPP OMENRAP_FULLTIME_POOLED_SUPP  \
2011 11810                          NaN                          NaN
2013 1360                           NaN                          NaN
     2217                           NaN                          NaN
2011 10510                          NaN                          NaN
     9115                           NaN                          NaN
2012 836                            NaN                          NaN
2013 6110                           NaN                          NaN
2012 3294                           NaN                          NaN
2011 6580                           NaN                          NaN
     9711                           NaN                          NaN

           OMAWDP8_FULLTIME_POOLED_SUPP OMENRUP_FULLTIME_POOLED_SUPP  \
2011 11810                          NaN                          NaN
2013 1360                           NaN                          NaN
     2217                           NaN                          NaN
2011 10510                          NaN                          NaN
     9115                           NaN                          NaN
2012 836                            NaN                          NaN
2013 6110                           NaN                          NaN
2012 3294                           NaN                          NaN
2011 6580                           NaN                          NaN
     9711                           NaN                          NaN

           OMENRYP_PARTTIME_POOLED_SUPP OMENRAP_PARTTIME_POOLED_SUPP  \
2011 11810                          NaN                          NaN
2013 1360                           NaN                          NaN
     2217                           NaN                          NaN
2011 10510                          NaN                          NaN
     9115                           NaN                          NaN
2012 836                            NaN                          NaN
2013 6110                           NaN                          NaN
2012 3294                           NaN                          NaN
2011 6580                           NaN                          NaN
     9711                           NaN                          NaN

           OMAWDP8_PARTTIME_POOLED_SUPP OMENRUP_PARTTIME_POOLED_SUPP
2011 11810                          NaN                          NaN
2013 1360                           NaN                          NaN
     2217                           NaN                          NaN
2011 10510                          NaN                          NaN
     9115                           NaN                          NaN
2012 836                            NaN                          NaN
2013 6110                           NaN                          NaN
2012 3294                           NaN                          NaN
2011 6580                           NaN                          NaN
     9711                           NaN                          NaN

[10 rows x 1977 columns]

In [ ]:
# Concatenation operation also have inner and outer methods
# If all df do not have identical columns -> Outer Join
# If all df needs to have only identical columns -> Inner Join

### Pandas Idioms Part-1

In [38]:
# Best solutions for particular problems - Idiomatic Python
# It is sort of sub-language in python
# Examples : Using Vectorization, Not using Iterative Loops when not required
# __pandorable__

In [39]:
import pandas as pd
import numpy as np
import timeit

df = pd.read_csv('datasets/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

### 1. Method Chaining 

Every method on an object returns a reference to that object. Hence you can condense many different operations on a DataFrame.

In [50]:
# Pull out the state and city names as a multiple index, and only for data which has a summary level of 50, which in this dataset is county-level data. Rename the column too to make it more readable.

(
    df
        .loc[
            df['SUMLEV'] == 50,
            ['STNAME', 'CTYNAME', 'ESTIMATESBASE2010']
        ]
        .dropna()
        .set_index(['STNAME', 'CTYNAME'])
        .rename(columns={'ESTIMATESBASE2010' : 'Estimates Base 2010'})
        .sample(15)
)

                                Estimates Base 2010
STNAME         CTYNAME
Texas          Brown County                   38106
North Carolina Richmond County                46639
Arizona        Maricopa County              3817357
Arkansas       Polk County                    20662
Missouri       Clark County                    7129
Texas          Potter County                 121073
Kentucky       Nelson County                  43437
Michigan       Mason County                   28705
Washington     Garfield County                 2266
Tennessee      Davidson County               626662
Ohio           Perry County                   36052
Minnesota      Brown County                   25893
North Carolina Hyde County                     5810
Indiana        Rush County                    17392
Minnesota      Goodhue County                 46183

In [ ]:
# Lesson -> Avoid "inplace = True", instead use assignment or method chaining

### Idiomatic Python - Part 2

In [56]:
# Using map()
def iseven(num):
    return (num % 2 == 0)

num = [2,3,4,5,6]
res = list(map(iseven, num))
print(res)

[True, False, True, False, True]

In [57]:
# Using apply() on df
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min': np.min(data), 'max': np.max(data)})

In [58]:
# apply takes function and axis
df.apply(min_max, axis='columns').sample(15)

          min      max
1755     8094     8362
1436     9150     9780
223   2202286  2361026
2160    13048    13421
1500    47485    48815
3086    16887    17053
801     27674    27964
766     69169    69648
1634     1745     1801
163      8970     9491
981      2503     2587
1119    24561    25420
2257     7185     7458
2488    56198    58229
2378    60135    61298

In [59]:
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    return row

df.apply(min_max, axis='columns').sample(10)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,max,min
2851,40,1,1,50,0,Vermont,Vermont,625741,625745,625984,...,-0.828064,-2.384568,-3.548825,0.282596,-1.469972,0.430784,-0.937877,-2.089704,627129,625984
2223,50,3,7,40,111,Oklahoma,Okmulgee County,40069,40069,40118,...,-3.514894,-9.031700,0.791584,-7.105951,-6.068083,-3.236737,-8.726403,1.098003,40118,39137
395,50,3,5,12,131,Florida,Walton County,55043,55043,55248,...,33.138001,28.714541,25.874131,5.176301,26.208374,34.251739,29.987436,27.105471,63508,55248
1488,50,3,6,28,125,Mississippi,Sharkey County,4916,4916,4880,...,-22.633527,-10.111876,-11.939650,-0.820008,-25.664907,-22.633527,-10.111876,-11.939650,4880,4585
2143,50,2,3,39,129,Ohio,Pickaway County,55698,55698,55745,...,-0.159580,4.151320,1.687467,2.702654,5.073070,0.035462,4.363302,1.898400,56998,55745
1125,50,3,6,21,229,Kentucky,Washington County,11717,11717,11742,...,-1.852320,2.013592,6.245316,3.826205,7.695235,-1.768123,2.097491,6.328587,12063,11742
438,50,3,5,13,83,Georgia,Dade County,16633,16633,16612,...,-1.938219,-8.281321,-6.068408,-2.229587,-5.374883,-1.453664,-7.611509,-5.394140,16612,16264
1985,50,3,5,37,123,North Carolina,Montgomery County,27798,27798,27744,...,-4.892723,-5.205584,3.311620,-1.114988,-9.691074,-4.820238,-4.950765,3.566360,27862,27410
2442,50,2,4,46,79,South Dakota,Lake County,11200,11200,11282,...,17.673172,16.655044,19.559902,23.856338,16.899245,19.432113,18.542068,21.403663,12622,11282
2946,50,3,5,51,167,Virginia,Russell County,28897,28896,28856,...,-2.294064,-6.220563,-3.506073,-2.782222,-6.273328,-2.152891,-6.042833,-3.327192,28856,27891

In [60]:
def get_state_region(x):
    northeast = [
        "Connecticut",
        "Maine",
        "Massachusetts",
        "New Hampshire",
        "Rhode Island",
        "Vermont",
        "New York",
        "New Jersey",
        "Pennsylvania",
    ]
    midwest = [
        "Illinois",
        "Indiana",
        "Michigan",
        "Ohio",
        "Wisconsin",
        "Iowa",
        "Kansas",
        "Minnesota",
        "Missouri",
        "Nebraska",
        "North Dakota",
        "South Dakota",
    ]
    south = [
        "Delaware",
        "Florida",
        "Georgia",
        "Maryland",
        "North Carolina",
        "South Carolina",
        "Virginia",
        "District of Columbia",
        "West Virginia",
        "Alabama",
        "Kentucky",
        "Mississippi",
        "Tennessee",
        "Arkansas",
        "Louisiana",
        "Oklahoma",
        "Texas",
    ]
    west = [
        "Arizona",
        "Colorado",
        "Idaho",
        "Montana",
        "Nevada",
        "New Mexico",
        "Utah",
        "Wyoming",
        "Alaska",
        "California",
        "Hawaii",
        "Oregon",
        "Washington",
    ]

    if x in northeast:
        return "Northeast"
    elif x in midwest:
        return "Midwest"
    elif x in south:
        return "South"
    else:
        return "West"

In [68]:
df['region'] = df['STNAME'].apply(lambda x : get_state_region(x))

df[['STNAME', 'region']].sample(10)

              STNAME   region
1085        Kentucky    South
2412    South Dakota  Midwest
1067        Kentucky    South
981           Kansas  Midwest
2100            Ohio  Midwest
2016  North Carolina    South
419          Georgia    South
1840      New Mexico     West
2804           Texas    South
2116            Ohio  Midwest

In [69]:
# Chained Version
(
    df
    .assign(
        region = df['STNAME'].apply(get_state_region)
    )

    [['STNAME', 'region']]

    .sample(10)
)

         STNAME     region
1891   New York  Northeast
414     Georgia      South
1132  Louisiana      South
2610      Texas      South
423     Georgia      South
47      Alabama      South
1669    Montana       West
1531   Missouri    Midwest
574       Idaho       West
1773   Nebraska    Midwest

### GroupBy - Part 1

In [71]:
# Split - Apply - Combine pattern

# Splitting
import pandas as pd
import numpy as np

df = pd.read_csv('datasets/census.csv')
df = df[df['SUMLEV'] == 50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [82]:
# Self - Learning Groupby Iteration Method
data = pd.read_csv('data.csv')
data = data.set_index('Index')
data.columns = [x.lower().strip() for x in data.columns]
data.head()

,customer id,first name,last name,company,city,country,phone 1,phone 2,email,subscription date,website
Index,,,,,,,,,,,
1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [94]:
data['subscription date'] = pd.to_datetime(data['subscription date']).dt.year
data['subscription date'].head()

Index
1    2020
2    2021
3    2020
4    2020
5    2021
Name: subscription date, dtype: int32

In [96]:
for val,frame in data.sample(10).groupby('subscription date'):
    print('YEAR : ', val)
    print('----------------------------------------------------------------')
    print('DATAFRAME : \n', frame)
    print('----------------------------------------------------------------')
    print('----------------------------------------------------------------')
    print('\n')

YEAR :  2020
----------------------------------------------------------------
DATAFRAME :
            customer id first name last name        company            city  \
Index
6      2d08FB17EE273F4      Aimee     Downs   Steele Group   Chavezborough
74     A3F76Be153Df4a3      Anita    Benson    Parrish Ltd     Skinnerport
91     5ef6d3eefdD43bE       Nina    Chavez  Byrd-Campbell  Cassidychester

                      country              phone 1              phone 2  \
Index
6      Bosnia and Herzegovina  (283)437-3886x88321         999-728-1637
74         Russian Federation   874.617.5668x69878   (399)820-6418x0071
91                     Bhutan         053-344-3205  +1-330-920-5422x571

                      email  subscription date                 website
Index
6       louis27@gilbert.com               2020  http://www.berger.net/
74     angie04@oconnell.com               2020     http://oconnor.com/
91     elliserica@frank.com               2020   https://www.pugh.com/
----------------------------------------------------------------
----------------------------------------------------------------


YEAR :  2021
----------------------------------------------------------------
DATAFRAME :
            customer id first name last name                          company  \
Index
25     eC1927Ca84E033e      Shane    Wilcox                       Tucker LLC
38     7a1Ee69F4fF4B4D     Jordan       Gay                  Glover and Sons
82     Ebdb6F6F7c90b69   Kathleen     Mckay         Coffey, Lamb and Johnson
66     fF1b6c9E8Fbf1ff   Fernando   Lambert                     Church-Banks
45     30Dfa48fe5Ede78     Rhonda     Frost  Herrera, Shepherd and Underwood

                  city                           country              phone 1  \
Index
25          Bryanville                           Albania  (429)005-9030x11004
38        South Walter                   Solomon Islands           7208417020
82      Lake Janiceton  Saint Vincent and the Grenadines        (733)910-9968
66          Lake Nancy                         Lithuania         497.829.9038
45     Lake Lindaburgh                            Monaco        (127)081-9339

                    phone 2                               email  \
Index
25             541-116-4501                 mariah88@santos.com
38               8035336772  tiffanydavies@harris-mcfarland.org
82       (691)247-4128x0665   chloelester@higgins-wilkinson.com
66               3863743398            fisherlinda@schaefer.net
45     +1-431-028-3337x3492            zkrueger@wolf-chavez.net

       subscription date                       website
Index
25                  2021        https://www.ramos.com/
38                  2021           http://www.lee.org/
82                  2021  http://www.owens-mooney.com/
66                  2021         https://www.vang.com/
45                  2021          http://www.khan.com/
----------------------------------------------------------------
----------------------------------------------------------------


YEAR :  2022
----------------------------------------------------------------
DATAFRAME :
            customer id first name   last name        company  \
Index
86     C6763c99d0bd16D       Emma  Cunningham   Stephens Inc
27     aBdfcF2c50b0bfD     Dakota       Poole  Simmons Group

                    city      country             phone 1             phone 2  \
Index
86     North Jillianview  New Zealand  128-059-0206x60217  (312)164-4545x2284
27          Michealshire      Belarus  (371)987-8576x4720        071-152-1376

                     email  subscription date                      website
Index
86     walter83@juarez.org               2022        http://www.reid.info/
27     stacey67@fields.org               2022  https://sanford-wilcox.biz/
----------------------------------------------------------------
----------------------------------------------------------------