### Merging One or More DataFrames

Full Outer Join -> Union<br>
Inner Join -> Intersection

In [15]:
import pandas as pd


stdf = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])

stdf = stdf.set_index('Name')

sdf = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])

sdf = sdf.set_index('Name')

In [16]:
stdf # Staff

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

In [17]:
sdf # Student

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [18]:
# James and Sally are both Students and Staff, but Mike is not

# Creating Union
pd.merge(stdf,sdf, how='outer', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [19]:
# Intersection
pd.merge(stdf,sdf, how='inner', left_index=True, right_index=True)

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

In [20]:
# left-Join
pd.merge(stdf,sdf, how='left', left_index=True, right_index=True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

In [21]:
# Right-Join
pd.merge(stdf,sdf, how='right', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering

In [10]:
# We need not use Indexes to merge df, param called "on"

# Remove index
stdf = stdf.reset_index()
sdf = sdf.reset_index()

# Join based on name column
pd.merge(stdf, sdf, how='right', on='Name') # Mistake

   index_x   Name            Role  index_y       School
0      2.0  James          Grader        0     Business
1      NaN   Mike             NaN        1          Law
2      1.0  Sally  Course liasion        2  Engineering

In [24]:
stdf = stdf.reset_index()
stdf

    Name            Role
0  Kelly  Director of HR
1  Sally  Course liasion
2  James          Grader

In [25]:
sdf = sdf.reset_index()
sdf

    Name       School
0  James     Business
1   Mike          Law
2  Sally  Engineering

In [27]:
pd.merge(stdf, sdf, how='right', on='Name')

# Always reset the index of dataframe before merging them

    Name            Role       School
0  James          Grader     Business
1   Mike             NaN          Law
2  Sally  Course liasion  Engineering

In [32]:
# Better to use df.reset_index(drop = True)
# This removes earlier index
# Example ->

sample = pd.DataFrame(
    [
        ['Charlie', 'Comedy'],
        ['Gabbar', 'Action'],
        ['Bheem', 'Cartoon']
    ],
    columns = ['Name', 'Type']
)
sample

      Name     Type
0  Charlie   Comedy
1   Gabbar   Action
2    Bheem  Cartoon

In [34]:
sample = sample.set_index('Name')
sample

            Type
Name
Charlie   Comedy
Gabbar    Action
Bheem    Cartoon

In [35]:
sample.reset_index(drop=True) # Dangerous

      Type
0   Comedy
1   Action
2  Cartoon

### Handling Conflicts between df

In [36]:
stdf = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 
                          'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 
                          'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 
                          'Location': 'Washington Avenue'}])
sdf = pd.DataFrame([{'Name': 'James', 'School': 'Business', 
                            'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 
                            'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 
                            'Location': '512 Wilson Crescent'}])