### Merging One or More DataFrames

Full Outer Join -> Union<br>
Inner Join -> Intersection

In [4]:
import pandas as pd


stdf = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])

stdf = stdf.set_index('Name')

sdf = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])

sdf = sdf.set_index('Name')

In [5]:
stdf # Staff

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

In [6]:
sdf # Student

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [3]:
# James and Sally are both Students and Staff, but Mike is not

# Creating Union
pd.merge(stdf,sdf, how='outer', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [7]:
# Intersection
pd.merge(stdf,sdf, how='inner', left_index=True, right_index=True)

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

In [8]:
# left-Join
pd.merge(stdf,sdf, how='left', left_index=True, right_index=True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

In [9]:
# Right-Join
pd.merge(stdf,sdf, how='right', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering